void spectrum_kminus_kminus_eta()
{
//=========Macro generated from canvas: c1_n2/c1_n2
//=========  (Thu Apr  5 15:28:28 2018) by ROOT version6.08/06
   TCanvas *c1_n2 = new TCanvas("c1_n2", "c1_n2",13,60,700,500);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1_n2->SetHighLightColor(2);
   c1_n2->Range(1.346914,-0.06348279,5.297531,0.3332847);
   c1_n2->SetFillColor(0);
   c1_n2->SetBorderMode(0);
   c1_n2->SetBorderSize(2);
   c1_n2->SetTickx(1);
   c1_n2->SetTicky(1);
   c1_n2->SetLeftMargin(0.14);
   c1_n2->SetRightMargin(0.05);
   c1_n2->SetTopMargin(0.05);
   c1_n2->SetBottomMargin(0.16);
   c1_n2->SetFrameLineWidth(2);
   c1_n2->SetFrameBorderMode(0);
   c1_n2->SetFrameLineWidth(2);
   c1_n2->SetFrameBorderMode(0);
   Double_t xAxis3[9] = {1.9, 2.4, 2.65, 3, 3.3, 3.5, 3.8, 4.5, 5.1}; 
   
   TH1F *kpipi_to_signal_k_spectra_from_eta__3 = new TH1F("kpipi_to_signal_k_spectra_from_eta__3","kpipi_to_signal_k_spectra_from_eta",8, xAxis3);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(0,0.0005370451);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(1,0.02789512);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(2,0.1385798);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(3,0.2066728);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(4,0.1765582);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(5,0.2238902);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(6,0.1563663);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(7,0.06715554);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(8,0.002881974);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(9,6.345264e-06);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(0,2.974986e-05);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(1,0.000120126);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(2,0.0003581875);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(3,0.0003179673);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(4,0.0002971209);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(5,0.0004035651);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(6,0.0002822292);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(7,0.0001685117);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(8,1.88712e-05);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(9,2.995024e-07);
   kpipi_to_signal_k_spectra_from_eta__3->SetMinimum(0);
   kpipi_to_signal_k_spectra_from_eta__3->SetMaximum(0.3134463);
   kpipi_to_signal_k_spectra_from_eta__3->SetEntries(3.196529e+07);
   kpipi_to_signal_k_spectra_from_eta__3->SetStats(0);
   kpipi_to_signal_k_spectra_from_eta__3->SetFillColor(4);
   kpipi_to_signal_k_spectra_from_eta__3->SetFillStyle(3004);
   kpipi_to_signal_k_spectra_from_eta__3->SetLineColor(4);
   kpipi_to_signal_k_spectra_from_eta__3->SetLineWidth(2);
   kpipi_to_signal_k_spectra_from_eta__3->SetMarkerStyle(22);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetTitle("#it{#eta}");
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetNdivisions(505);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetLabelFont(132);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetLabelOffset(0.01);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetLabelSize(0.06);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetTitleSize(0.072);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetTitleOffset(0.95);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetTitleFont(132);
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetTitle("Candidates (arb. units)");
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetLabelFont(132);
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetLabelOffset(0.01);
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetLabelSize(0.06);
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetTitleSize(0.072);
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetTitleOffset(0.95);
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetTitleFont(132);
   kpipi_to_signal_k_spectra_from_eta__3->GetZaxis()->SetLabelFont(132);
   kpipi_to_signal_k_spectra_from_eta__3->GetZaxis()->SetLabelSize(0.06);
   kpipi_to_signal_k_spectra_from_eta__3->GetZaxis()->SetTitleSize(0.072);
   kpipi_to_signal_k_spectra_from_eta__3->GetZaxis()->SetTitleOffset(1.2);
   kpipi_to_signal_k_spectra_from_eta__3->GetZaxis()->SetTitleFont(132);
   kpipi_to_signal_k_spectra_from_eta__3->Draw("HIST");
   Double_t xAxis4[9] = {1.9, 2.4, 2.65, 3, 3.3, 3.5, 3.8, 4.5, 5.1}; 
   
   TH1F *kpipi_to_signal_k_spectra_to_eta__4 = new TH1F("kpipi_to_signal_k_spectra_to_eta__4","kpipi_to_signal_k_spectra_to_eta",8, xAxis4);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(0,-0.0003907233);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(1,0.06091842);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(2,0.1571807);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(3,0.2029129);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(4,0.1526049);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(5,0.1739439);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(6,0.161471);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(7,0.07171204);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(8,0.0192562);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(0,0.0003907233);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(1,0.0202153);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(2,0.05078845);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(3,0.05085248);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(4,0.05594416);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(5,0.07121839);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(6,0.04763787);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(7,0.01990694);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(8,0.009184725);
   kpipi_to_signal_k_spectra_to_eta__4->SetEntries(535);
   kpipi_to_signal_k_spectra_to_eta__4->SetStats(0);
   kpipi_to_signal_k_spectra_to_eta__4->SetFillColor(2);
   kpipi_to_signal_k_spectra_to_eta__4->SetFillStyle(3005);
   kpipi_to_signal_k_spectra_to_eta__4->SetLineColor(2);
   kpipi_to_signal_k_spectra_to_eta__4->SetLineWidth(2);
   kpipi_to_signal_k_spectra_to_eta__4->SetMarkerStyle(23);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetNdivisions(505);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetLabelFont(132);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetLabelOffset(0.01);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetLabelSize(0.06);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetTitleSize(0.072);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetTitleOffset(0.95);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetTitleFont(132);
   kpipi_to_signal_k_spectra_to_eta__4->GetYaxis()->SetLabelFont(132);
   kpipi_to_signal_k_spectra_to_eta__4->GetYaxis()->SetLabelOffset(0.01);
   kpipi_to_signal_k_spectra_to_eta__4->GetYaxis()->SetLabelSize(0.06);
   kpipi_to_signal_k_spectra_to_eta__4->GetYaxis()->SetTitleSize(0.072);
   kpipi_to_signal_k_spectra_to_eta__4->GetYaxis()->SetTitleOffset(0.95);
   kpipi_to_signal_k_spectra_to_eta__4->GetYaxis()->SetTitleFont(132);
   kpipi_to_signal_k_spectra_to_eta__4->GetZaxis()->SetLabelFont(132);
   kpipi_to_signal_k_spectra_to_eta__4->GetZaxis()->SetLabelSize(0.06);
   kpipi_to_signal_k_spectra_to_eta__4->GetZaxis()->SetTitleSize(0.072);
   kpipi_to_signal_k_spectra_to_eta__4->GetZaxis()->SetTitleOffset(1.2);
   kpipi_to_signal_k_spectra_to_eta__4->GetZaxis()->SetTitleFont(132);
   kpipi_to_signal_k_spectra_to_eta__4->Draw("HIST SAME");
   
   TLegend *leg = new TLegend(0.555,0.73,0.89,0.92,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(132);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(2);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("kpipi_to_signal_k_spectra_from_eta","[#it{D^{#pm}#rightarrowK^{#mp}#pi^{#pm}#pi^{#pm}}] K^{#mp}","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(3004);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   entry=leg->AddEntry("kpipi_to_signal_k_spectra_to_eta","[#it{Signal}] K^{#mp}","f");
   entry->SetFillColor(2);
   entry->SetFillStyle(3005);
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   leg->Draw();
   c1_n2->Modified();
   c1_n2->cd();
   c1_n2->SetSelected(c1_n2);
}
