void spectrum_piplus_piplus_eta()
{
//=========Macro generated from canvas: c1_n2/c1_n2
//=========  (Thu Apr  5 14:47:25 2018) by ROOT version6.08/06
   TCanvas *c1_n2 = new TCanvas("c1_n2", "c1_n2",13,60,700,500);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1_n2->SetHighLightColor(2);
   c1_n2->Range(1.346914,-0.07232952,5.297531,0.37973);
   c1_n2->SetFillColor(0);
   c1_n2->SetBorderMode(0);
   c1_n2->SetBorderSize(2);
   c1_n2->SetTickx(1);
   c1_n2->SetTicky(1);
   c1_n2->SetLeftMargin(0.14);
   c1_n2->SetRightMargin(0.05);
   c1_n2->SetTopMargin(0.05);
   c1_n2->SetBottomMargin(0.16);
   c1_n2->SetFrameLineWidth(2);
   c1_n2->SetFrameBorderMode(0);
   c1_n2->SetFrameLineWidth(2);
   c1_n2->SetFrameBorderMode(0);
   Double_t xAxis7[9] = {1.9, 2.4, 2.65, 3, 3.3, 3.5, 3.8, 4.5, 5.1}; 
   
   TH1F *kpipi_to_signal_pi_spectra_from_eta__7 = new TH1F("kpipi_to_signal_pi_spectra_from_eta__7","kpipi_to_signal_pi_spectra_from_eta",8, xAxis7);
   kpipi_to_signal_pi_spectra_from_eta__7->SetBinContent(0,0.0001971163);
   kpipi_to_signal_pi_spectra_from_eta__7->SetBinContent(1,0.06158233);
   kpipi_to_signal_pi_spectra_from_eta__7->SetBinContent(2,0.1360483);
   kpipi_to_signal_pi_spectra_from_eta__7->SetBinContent(3,0.1963198);
   kpipi_to_signal_pi_spectra_from_eta__7->SetBinContent(4,0.2550907);
   kpipi_to_signal_pi_spectra_from_eta__7->SetBinContent(5,0.223738);
   kpipi_to_signal_pi_spectra_from_eta__7->SetBinContent(6,0.09913568);
   kpipi_to_signal_pi_spectra_from_eta__7->SetBinContent(7,0.02747711);
   kpipi_to_signal_pi_spectra_from_eta__7->SetBinContent(8,0.0006080323);
   kpipi_to_signal_pi_spectra_from_eta__7->SetBinContent(9,1.115696e-06);
   kpipi_to_signal_pi_spectra_from_eta__7->SetBinError(0,1.404024e-06);
   kpipi_to_signal_pi_spectra_from_eta__7->SetBinError(1,0.0001473405);
   kpipi_to_signal_pi_spectra_from_eta__7->SetBinError(2,0.0002392016);
   kpipi_to_signal_pi_spectra_from_eta__7->SetBinError(3,0.0002145948);
   kpipi_to_signal_pi_spectra_from_eta__7->SetBinError(4,0.0002499397);
   kpipi_to_signal_pi_spectra_from_eta__7->SetBinError(5,0.000330319);
   kpipi_to_signal_pi_spectra_from_eta__7->SetBinError(6,0.0001833434);
   kpipi_to_signal_pi_spectra_from_eta__7->SetBinError(7,8.00354e-05);
   kpipi_to_signal_pi_spectra_from_eta__7->SetBinError(8,5.147358e-06);
   kpipi_to_signal_pi_spectra_from_eta__7->SetBinError(9,3.615166e-08);
   kpipi_to_signal_pi_spectra_from_eta__7->SetMinimum(0);
   kpipi_to_signal_pi_spectra_from_eta__7->SetMaximum(0.357127);
   kpipi_to_signal_pi_spectra_from_eta__7->SetEntries(4.332413e+07);
   kpipi_to_signal_pi_spectra_from_eta__7->SetStats(0);
   kpipi_to_signal_pi_spectra_from_eta__7->SetFillColor(4);
   kpipi_to_signal_pi_spectra_from_eta__7->SetFillStyle(3004);
   kpipi_to_signal_pi_spectra_from_eta__7->SetLineColor(4);
   kpipi_to_signal_pi_spectra_from_eta__7->SetLineWidth(2);
   kpipi_to_signal_pi_spectra_from_eta__7->SetMarkerStyle(22);
   kpipi_to_signal_pi_spectra_from_eta__7->GetXaxis()->SetTitle("#it{#eta}");
   kpipi_to_signal_pi_spectra_from_eta__7->GetXaxis()->SetNdivisions(505);
   kpipi_to_signal_pi_spectra_from_eta__7->GetXaxis()->SetLabelFont(132);
   kpipi_to_signal_pi_spectra_from_eta__7->GetXaxis()->SetLabelOffset(0.01);
   kpipi_to_signal_pi_spectra_from_eta__7->GetXaxis()->SetLabelSize(0.06);
   kpipi_to_signal_pi_spectra_from_eta__7->GetXaxis()->SetTitleSize(0.072);
   kpipi_to_signal_pi_spectra_from_eta__7->GetXaxis()->SetTitleOffset(0.95);
   kpipi_to_signal_pi_spectra_from_eta__7->GetXaxis()->SetTitleFont(132);
   kpipi_to_signal_pi_spectra_from_eta__7->GetYaxis()->SetTitle("Candidates (arb. units)");
   kpipi_to_signal_pi_spectra_from_eta__7->GetYaxis()->SetLabelFont(132);
   kpipi_to_signal_pi_spectra_from_eta__7->GetYaxis()->SetLabelOffset(0.01);
   kpipi_to_signal_pi_spectra_from_eta__7->GetYaxis()->SetLabelSize(0.06);
   kpipi_to_signal_pi_spectra_from_eta__7->GetYaxis()->SetTitleSize(0.072);
   kpipi_to_signal_pi_spectra_from_eta__7->GetYaxis()->SetTitleOffset(0.95);
   kpipi_to_signal_pi_spectra_from_eta__7->GetYaxis()->SetTitleFont(132);
   kpipi_to_signal_pi_spectra_from_eta__7->GetZaxis()->SetLabelFont(132);
   kpipi_to_signal_pi_spectra_from_eta__7->GetZaxis()->SetLabelSize(0.06);
   kpipi_to_signal_pi_spectra_from_eta__7->GetZaxis()->SetTitleSize(0.072);
   kpipi_to_signal_pi_spectra_from_eta__7->GetZaxis()->SetTitleOffset(1.2);
   kpipi_to_signal_pi_spectra_from_eta__7->GetZaxis()->SetTitleFont(132);
   kpipi_to_signal_pi_spectra_from_eta__7->Draw("HIST");
   Double_t xAxis8[9] = {1.9, 2.4, 2.65, 3, 3.3, 3.5, 3.8, 4.5, 5.1}; 
   
   TH1F *kpipi_to_signal_pi_spectra_to_eta__8 = new TH1F("kpipi_to_signal_pi_spectra_to_eta__8","kpipi_to_signal_pi_spectra_to_eta",8, xAxis8);
   kpipi_to_signal_pi_spectra_to_eta__8->SetBinContent(0,0.001944813);
   kpipi_to_signal_pi_spectra_to_eta__8->SetBinContent(1,0.07717039);
   kpipi_to_signal_pi_spectra_to_eta__8->SetBinContent(2,0.1386358);
   kpipi_to_signal_pi_spectra_to_eta__8->SetBinContent(3,0.1662828);
   kpipi_to_signal_pi_spectra_to_eta__8->SetBinContent(4,0.2234688);
   kpipi_to_signal_pi_spectra_to_eta__8->SetBinContent(5,0.2281113);
   kpipi_to_signal_pi_spectra_to_eta__8->SetBinContent(6,0.1138258);
   kpipi_to_signal_pi_spectra_to_eta__8->SetBinContent(7,0.05266886);
   kpipi_to_signal_pi_spectra_to_eta__8->SetBinContent(8,-0.0001637536);
   kpipi_to_signal_pi_spectra_to_eta__8->SetBinError(0,0.001849613);
   kpipi_to_signal_pi_spectra_to_eta__8->SetBinError(1,0.017135);
   kpipi_to_signal_pi_spectra_to_eta__8->SetBinError(2,0.03536422);
   kpipi_to_signal_pi_spectra_to_eta__8->SetBinError(3,0.03481018);
   kpipi_to_signal_pi_spectra_to_eta__8->SetBinError(4,0.04569151);
   kpipi_to_signal_pi_spectra_to_eta__8->SetBinError(5,0.0543584);
   kpipi_to_signal_pi_spectra_to_eta__8->SetBinError(6,0.03379739);
   kpipi_to_signal_pi_spectra_to_eta__8->SetBinError(7,0.01385123);
   kpipi_to_signal_pi_spectra_to_eta__8->SetBinError(8,0.0003293977);
   kpipi_to_signal_pi_spectra_to_eta__8->SetEntries(894);
   kpipi_to_signal_pi_spectra_to_eta__8->SetStats(0);
   kpipi_to_signal_pi_spectra_to_eta__8->SetFillColor(2);
   kpipi_to_signal_pi_spectra_to_eta__8->SetFillStyle(3005);
   kpipi_to_signal_pi_spectra_to_eta__8->SetLineColor(2);
   kpipi_to_signal_pi_spectra_to_eta__8->SetLineWidth(2);
   kpipi_to_signal_pi_spectra_to_eta__8->SetMarkerStyle(23);
   kpipi_to_signal_pi_spectra_to_eta__8->GetXaxis()->SetNdivisions(505);
   kpipi_to_signal_pi_spectra_to_eta__8->GetXaxis()->SetLabelFont(132);
   kpipi_to_signal_pi_spectra_to_eta__8->GetXaxis()->SetLabelOffset(0.01);
   kpipi_to_signal_pi_spectra_to_eta__8->GetXaxis()->SetLabelSize(0.06);
   kpipi_to_signal_pi_spectra_to_eta__8->GetXaxis()->SetTitleSize(0.072);
   kpipi_to_signal_pi_spectra_to_eta__8->GetXaxis()->SetTitleOffset(0.95);
   kpipi_to_signal_pi_spectra_to_eta__8->GetXaxis()->SetTitleFont(132);
   kpipi_to_signal_pi_spectra_to_eta__8->GetYaxis()->SetLabelFont(132);
   kpipi_to_signal_pi_spectra_to_eta__8->GetYaxis()->SetLabelOffset(0.01);
   kpipi_to_signal_pi_spectra_to_eta__8->GetYaxis()->SetLabelSize(0.06);
   kpipi_to_signal_pi_spectra_to_eta__8->GetYaxis()->SetTitleSize(0.072);
   kpipi_to_signal_pi_spectra_to_eta__8->GetYaxis()->SetTitleOffset(0.95);
   kpipi_to_signal_pi_spectra_to_eta__8->GetYaxis()->SetTitleFont(132);
   kpipi_to_signal_pi_spectra_to_eta__8->GetZaxis()->SetLabelFont(132);
   kpipi_to_signal_pi_spectra_to_eta__8->GetZaxis()->SetLabelSize(0.06);
   kpipi_to_signal_pi_spectra_to_eta__8->GetZaxis()->SetTitleSize(0.072);
   kpipi_to_signal_pi_spectra_to_eta__8->GetZaxis()->SetTitleOffset(1.2);
   kpipi_to_signal_pi_spectra_to_eta__8->GetZaxis()->SetTitleFont(132);
   kpipi_to_signal_pi_spectra_to_eta__8->Draw("HIST SAME");
   
   TLegend *leg = new TLegend(0.555,0.73,0.89,0.92,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(132);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(2);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("kpipi_to_signal_pi_spectra_from_eta","[#it{D^{#pm}#rightarrowK^{#mp}#pi^{#pm}#pi^{#pm}}] #pi^{#pm}","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(3004);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   entry=leg->AddEntry("kpipi_to_signal_pi_spectra_to_eta","[#it{Signal}] #pi^{#pm}","f");
   entry->SetFillColor(2);
   entry->SetFillStyle(3005);
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   leg->Draw();
   c1_n2->Modified();
   c1_n2->cd();
   c1_n2->SetSelected(c1_n2);
}
