void spectrum_kminus_kminus_eta()
{
//=========Macro generated from canvas: c1_n2/c1_n2
//=========  (Thu Apr  5 16:04:24 2018) by ROOT version6.08/06
   TCanvas *c1_n2 = new TCanvas("c1_n2", "c1_n2",13,60,700,500);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1_n2->SetHighLightColor(2);
   c1_n2->Range(1.346914,-0.09173717,5.297531,0.4816202);
   c1_n2->SetFillColor(0);
   c1_n2->SetBorderMode(0);
   c1_n2->SetBorderSize(2);
   c1_n2->SetTickx(1);
   c1_n2->SetTicky(1);
   c1_n2->SetLeftMargin(0.14);
   c1_n2->SetRightMargin(0.05);
   c1_n2->SetTopMargin(0.05);
   c1_n2->SetBottomMargin(0.16);
   c1_n2->SetFrameLineWidth(2);
   c1_n2->SetFrameBorderMode(0);
   c1_n2->SetFrameLineWidth(2);
   c1_n2->SetFrameBorderMode(0);
   Double_t xAxis3[9] = {1.9, 2.4, 2.65, 3, 3.3, 3.5, 3.8, 4.5, 5.1}; 
   
   TH1F *kpipi_to_signal_k_spectra_from_eta__3 = new TH1F("kpipi_to_signal_k_spectra_from_eta__3","kpipi_to_signal_k_spectra_from_eta",8, xAxis3);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(0,2.471405e-05);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(1,0.02448126);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(2,0.1320276);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(3,0.2026161);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(4,0.3235373);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(5,0.1773145);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(6,0.1084013);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(7,0.03094348);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(8,0.0006784322);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(9,8.106723e-07);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(0,6.278478e-07);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(1,0.0001165229);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(2,0.000407578);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(3,0.0003255537);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(4,0.0004318781);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(5,0.0004070859);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(6,0.0002440331);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(7,9.75999e-05);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(8,9.080659e-06);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(9,6.268851e-08);
   kpipi_to_signal_k_spectra_from_eta__3->SetMinimum(0);
   kpipi_to_signal_k_spectra_from_eta__3->SetMaximum(0.4529523);
   kpipi_to_signal_k_spectra_from_eta__3->SetEntries(1.57053e+07);
   kpipi_to_signal_k_spectra_from_eta__3->SetStats(0);
   kpipi_to_signal_k_spectra_from_eta__3->SetFillColor(4);
   kpipi_to_signal_k_spectra_from_eta__3->SetFillStyle(3004);
   kpipi_to_signal_k_spectra_from_eta__3->SetLineColor(4);
   kpipi_to_signal_k_spectra_from_eta__3->SetLineWidth(2);
   kpipi_to_signal_k_spectra_from_eta__3->SetMarkerStyle(22);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetTitle("#it{#eta}");
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetNdivisions(505);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetLabelFont(132);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetLabelOffset(0.01);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetLabelSize(0.06);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetTitleSize(0.072);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetTitleOffset(0.95);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetTitleFont(132);
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetTitle("Candidates (arb. units)");
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetLabelFont(132);
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetLabelOffset(0.01);
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetLabelSize(0.06);
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetTitleSize(0.072);
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetTitleOffset(0.95);
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetTitleFont(132);
   kpipi_to_signal_k_spectra_from_eta__3->GetZaxis()->SetLabelFont(132);
   kpipi_to_signal_k_spectra_from_eta__3->GetZaxis()->SetLabelSize(0.06);
   kpipi_to_signal_k_spectra_from_eta__3->GetZaxis()->SetTitleSize(0.072);
   kpipi_to_signal_k_spectra_from_eta__3->GetZaxis()->SetTitleOffset(1.2);
   kpipi_to_signal_k_spectra_from_eta__3->GetZaxis()->SetTitleFont(132);
   kpipi_to_signal_k_spectra_from_eta__3->Draw("HIST");
   Double_t xAxis4[9] = {1.9, 2.4, 2.65, 3, 3.3, 3.5, 3.8, 4.5, 5.1}; 
   
   TH1F *kpipi_to_signal_k_spectra_to_eta__4 = new TH1F("kpipi_to_signal_k_spectra_to_eta__4","kpipi_to_signal_k_spectra_to_eta",8, xAxis4);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(0,-3.960991e-05);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(1,0.05797907);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(2,0.1480619);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(3,0.1847896);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(4,0.3089233);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(5,0.1605375);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(6,0.1015084);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(7,0.03864098);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(8,-0.0004407803);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(0,0.0002549311);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(1,0.01112658);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(2,0.02709068);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(3,0.02621123);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(4,0.03285303);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(5,0.0345589);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(6,0.02473309);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(7,0.00926607);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(8,0.001287493);
   kpipi_to_signal_k_spectra_to_eta__4->SetEntries(2734);
   kpipi_to_signal_k_spectra_to_eta__4->SetStats(0);
   kpipi_to_signal_k_spectra_to_eta__4->SetFillColor(2);
   kpipi_to_signal_k_spectra_to_eta__4->SetFillStyle(3005);
   kpipi_to_signal_k_spectra_to_eta__4->SetLineColor(2);
   kpipi_to_signal_k_spectra_to_eta__4->SetLineWidth(2);
   kpipi_to_signal_k_spectra_to_eta__4->SetMarkerStyle(23);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetNdivisions(505);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetLabelFont(132);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetLabelOffset(0.01);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetLabelSize(0.06);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetTitleSize(0.072);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetTitleOffset(0.95);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetTitleFont(132);
   kpipi_to_signal_k_spectra_to_eta__4->GetYaxis()->SetLabelFont(132);
   kpipi_to_signal_k_spectra_to_eta__4->GetYaxis()->SetLabelOffset(0.01);
   kpipi_to_signal_k_spectra_to_eta__4->GetYaxis()->SetLabelSize(0.06);
   kpipi_to_signal_k_spectra_to_eta__4->GetYaxis()->SetTitleSize(0.072);
   kpipi_to_signal_k_spectra_to_eta__4->GetYaxis()->SetTitleOffset(0.95);
   kpipi_to_signal_k_spectra_to_eta__4->GetYaxis()->SetTitleFont(132);
   kpipi_to_signal_k_spectra_to_eta__4->GetZaxis()->SetLabelFont(132);
   kpipi_to_signal_k_spectra_to_eta__4->GetZaxis()->SetLabelSize(0.06);
   kpipi_to_signal_k_spectra_to_eta__4->GetZaxis()->SetTitleSize(0.072);
   kpipi_to_signal_k_spectra_to_eta__4->GetZaxis()->SetTitleOffset(1.2);
   kpipi_to_signal_k_spectra_to_eta__4->GetZaxis()->SetTitleFont(132);
   kpipi_to_signal_k_spectra_to_eta__4->Draw("HIST SAME");
   
   TLegend *leg = new TLegend(0.555,0.73,0.89,0.92,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(132);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(2);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("kpipi_to_signal_k_spectra_from_eta","[#it{D^{#pm}#rightarrowK^{#mp}#pi^{#pm}#pi^{#pm}}] K^{#mp}","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(3004);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   entry=leg->AddEntry("kpipi_to_signal_k_spectra_to_eta","[#it{Signal}] K^{#mp}","f");
   entry->SetFillColor(2);
   entry->SetFillStyle(3005);
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   leg->Draw();
   c1_n2->Modified();
   c1_n2->cd();
   c1_n2->SetSelected(c1_n2);
}
