void spectrum_kminus_kminus_eta()
{
//=========Macro generated from canvas: c1_n2/c1_n2
//=========  (Thu Apr  5 15:53:27 2018) by ROOT version6.08/06
   TCanvas *c1_n2 = new TCanvas("c1_n2", "c1_n2",13,60,700,500);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1_n2->SetHighLightColor(2);
   c1_n2->Range(1.346914,-0.06479804,5.297531,0.3401897);
   c1_n2->SetFillColor(0);
   c1_n2->SetBorderMode(0);
   c1_n2->SetBorderSize(2);
   c1_n2->SetTickx(1);
   c1_n2->SetTicky(1);
   c1_n2->SetLeftMargin(0.14);
   c1_n2->SetRightMargin(0.05);
   c1_n2->SetTopMargin(0.05);
   c1_n2->SetBottomMargin(0.16);
   c1_n2->SetFrameLineWidth(2);
   c1_n2->SetFrameBorderMode(0);
   c1_n2->SetFrameLineWidth(2);
   c1_n2->SetFrameBorderMode(0);
   Double_t xAxis3[9] = {1.9, 2.4, 2.65, 3, 3.3, 3.5, 3.8, 4.5, 5.1}; 
   
   TH1F *kpipi_to_signal_k_spectra_from_eta__3 = new TH1F("kpipi_to_signal_k_spectra_from_eta__3","kpipi_to_signal_k_spectra_from_eta",8, xAxis3);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(0,0.0002775277);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(1,0.02879495);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(2,0.1181435);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(3,0.2080813);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(4,0.2285288);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(5,0.2261254);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(6,0.1526605);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(7,0.03527162);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(8,0.002393951);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinContent(9,1.116784e-05);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(0,2.029039e-05);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(1,0.0001022799);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(2,0.0002886697);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(3,0.0002796338);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(4,0.0003086012);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(5,0.0003801498);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(6,0.0002677679);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(7,9.664339e-05);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(8,1.279606e-05);
   kpipi_to_signal_k_spectra_from_eta__3->SetBinError(9,4.900649e-07);
   kpipi_to_signal_k_spectra_from_eta__3->SetMinimum(0);
   kpipi_to_signal_k_spectra_from_eta__3->SetMaximum(0.3199403);
   kpipi_to_signal_k_spectra_from_eta__3->SetEntries(1.31091e+07);
   kpipi_to_signal_k_spectra_from_eta__3->SetStats(0);
   kpipi_to_signal_k_spectra_from_eta__3->SetFillColor(4);
   kpipi_to_signal_k_spectra_from_eta__3->SetFillStyle(3004);
   kpipi_to_signal_k_spectra_from_eta__3->SetLineColor(4);
   kpipi_to_signal_k_spectra_from_eta__3->SetLineWidth(2);
   kpipi_to_signal_k_spectra_from_eta__3->SetMarkerStyle(22);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetTitle("#it{#eta}");
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetNdivisions(505);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetLabelFont(132);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetLabelOffset(0.01);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetLabelSize(0.06);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetTitleSize(0.072);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetTitleOffset(0.95);
   kpipi_to_signal_k_spectra_from_eta__3->GetXaxis()->SetTitleFont(132);
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetTitle("Candidates (arb. units)");
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetLabelFont(132);
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetLabelOffset(0.01);
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetLabelSize(0.06);
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetTitleSize(0.072);
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetTitleOffset(0.95);
   kpipi_to_signal_k_spectra_from_eta__3->GetYaxis()->SetTitleFont(132);
   kpipi_to_signal_k_spectra_from_eta__3->GetZaxis()->SetLabelFont(132);
   kpipi_to_signal_k_spectra_from_eta__3->GetZaxis()->SetLabelSize(0.06);
   kpipi_to_signal_k_spectra_from_eta__3->GetZaxis()->SetTitleSize(0.072);
   kpipi_to_signal_k_spectra_from_eta__3->GetZaxis()->SetTitleOffset(1.2);
   kpipi_to_signal_k_spectra_from_eta__3->GetZaxis()->SetTitleFont(132);
   kpipi_to_signal_k_spectra_from_eta__3->Draw("HIST");
   Double_t xAxis4[9] = {1.9, 2.4, 2.65, 3, 3.3, 3.5, 3.8, 4.5, 5.1}; 
   
   TH1F *kpipi_to_signal_k_spectra_to_eta__4 = new TH1F("kpipi_to_signal_k_spectra_to_eta__4","kpipi_to_signal_k_spectra_to_eta",8, xAxis4);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(0,0.0007008974);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(1,0.05058945);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(2,0.1381998);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(3,0.1956103);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(4,0.2018437);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(5,0.2170864);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(6,0.1525611);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(7,0.03941247);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinContent(8,0.004696702);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(0,0.0005148878);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(1,0.006720779);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(2,0.01606888);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(3,0.0166998);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(4,0.01839957);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(5,0.022696);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(6,0.0163878);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(7,0.005928049);
   kpipi_to_signal_k_spectra_to_eta__4->SetBinError(8,0.002369739);
   kpipi_to_signal_k_spectra_to_eta__4->SetEntries(4703);
   kpipi_to_signal_k_spectra_to_eta__4->SetStats(0);
   kpipi_to_signal_k_spectra_to_eta__4->SetFillColor(2);
   kpipi_to_signal_k_spectra_to_eta__4->SetFillStyle(3005);
   kpipi_to_signal_k_spectra_to_eta__4->SetLineColor(2);
   kpipi_to_signal_k_spectra_to_eta__4->SetLineWidth(2);
   kpipi_to_signal_k_spectra_to_eta__4->SetMarkerStyle(23);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetNdivisions(505);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetLabelFont(132);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetLabelOffset(0.01);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetLabelSize(0.06);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetTitleSize(0.072);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetTitleOffset(0.95);
   kpipi_to_signal_k_spectra_to_eta__4->GetXaxis()->SetTitleFont(132);
   kpipi_to_signal_k_spectra_to_eta__4->GetYaxis()->SetLabelFont(132);
   kpipi_to_signal_k_spectra_to_eta__4->GetYaxis()->SetLabelOffset(0.01);
   kpipi_to_signal_k_spectra_to_eta__4->GetYaxis()->SetLabelSize(0.06);
   kpipi_to_signal_k_spectra_to_eta__4->GetYaxis()->SetTitleSize(0.072);
   kpipi_to_signal_k_spectra_to_eta__4->GetYaxis()->SetTitleOffset(0.95);
   kpipi_to_signal_k_spectra_to_eta__4->GetYaxis()->SetTitleFont(132);
   kpipi_to_signal_k_spectra_to_eta__4->GetZaxis()->SetLabelFont(132);
   kpipi_to_signal_k_spectra_to_eta__4->GetZaxis()->SetLabelSize(0.06);
   kpipi_to_signal_k_spectra_to_eta__4->GetZaxis()->SetTitleSize(0.072);
   kpipi_to_signal_k_spectra_to_eta__4->GetZaxis()->SetTitleOffset(1.2);
   kpipi_to_signal_k_spectra_to_eta__4->GetZaxis()->SetTitleFont(132);
   kpipi_to_signal_k_spectra_to_eta__4->Draw("HIST SAME");
   
   TLegend *leg = new TLegend(0.555,0.73,0.89,0.92,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(132);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(2);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("kpipi_to_signal_k_spectra_from_eta","[#it{D^{#pm}#rightarrowK^{#mp}#pi^{#pm}#pi^{#pm}}] K^{#mp}","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(3004);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   entry=leg->AddEntry("kpipi_to_signal_k_spectra_to_eta","[#it{Signal}] K^{#mp}","f");
   entry->SetFillColor(2);
   entry->SetFillStyle(3005);
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   leg->Draw();
   c1_n2->Modified();
   c1_n2->cd();
   c1_n2->SetSelected(c1_n2);
}
